---
title: "lab3"
author: "Ayimen H."
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r}
# Base population
total_pop <- 3391405  # Total aged 21-64

# (a) What is the probability that that individual is older than 54?
a_num <- 490185       # 55-64 years
cat("(a) Probability > 54: ", round((a_num / total_pop) * 100, 2), "%\n")

# (b) What is the probability that that individual is older than 44?
b_num <- 835590 + 490185  # 45-54 + 55-64
cat("(b) Probability > 44: ", round((b_num / total_pop) * 100, 2), "%\n")

# (c) What is the probability that the individual is not a high school graduate?
c_num <- 278530       # Non-graduates
cat("(c) Not HS grad: ", round((c_num / total_pop) * 100, 2), "%\n")

# (d) What is the probability that the individual has completed at least a
# bachelor’s degree?
d_num <- 652845 + 307405  # Bachelor's + Advanced
cat("(d) >= Bachelor's: ", round((d_num / total_pop) * 100, 2), "%\n")

# (e) What is the probability that the individual has completed an advanced
# degree and worked full-time year-round in 1999?
e_num <- 194560       # Advanced degree + full-time
cat("(e) Advanced & FT: ", round((e_num / total_pop) * 100, 2), "%\n")

# (f) What is the probability that the individual has completed an advanced
# degree or worked full-time year-round in 1999?
f_num <- 307405 + 1735245 - 194560  # Advanced + FT - overlap
cat("(f) Advanced | FT: ", round((f_num / total_pop) * 100, 2), "%\n")

# (g) What is the probability that the individual has completed at least
# high school and worked full-time year-round in 1999?
g_num <- 1735245 - 81375  # FT workers - non-grad FT workers
cat("(g) >= HS & FT: ", round((g_num / total_pop) * 100, 2), "%\n")

# (h) Suppose that we know that an individual did not work full-time year-round
# in 1999. What is the probability that they did not graduate high school?
h_num <- 278530 - 81375   # Non-grads not working FT
h_den <- total_pop - 1735245  # Total not working FT
cat("(h) No HS & No FT: ", round((h_num / h_den) * 100, 2), "%\n")

# (i) Does it appear that biological sex is independent of completing high school?
men_nongrad <- 144875
men_total <- 1678835

women_nongrad <- 133660
women_total <- 1712570

total_nongrad <- men_nongrad + women_nongrad

p_male <- men_total / total_pop
p_nongrad <- total_nongrad / total_pop

expected_joint_p <- p_male * p_nongrad
actual_joint_p <- men_nongrad / total_pop

cat("(i) Male non-grad rate: ", round((men_nongrad / men_total) * 100, 2), "%\n")
cat("Female non-grad rate: ", round((women_nongrad / women_total) * 100, 2), "%\n")

cat("Expected P(Male inter Not Grad) if independent: ", round(expected_joint_p * 100, 2), "%\n")
cat("Actual P(Male inter Not Grad): ", round(actual_joint_p * 100, 2), "%\n")

cat("Conclusion: Biological sex and HS completion are NOT independent\n")


# (j) What percentage of people aged 25 to 44 years are female?
j_num <- 406110 + 488830  # Women 25-34 + 35-44
j_den <- 809400 + 966115   # Total 25-44
cat("(j) Female 25-44: ", round((j_num / j_den) * 100, 2), "%\n")
```

